### ISSUE TITLE
Support for the Illumina Mouse Array

### ISSUE THREAD

**Issue by schmic05** [epigen/RnBeads#14]
Supporting the mouse array was requested by a number of users and will be a great addition to the package. Here is the info for the array (https://emea.illumina.com/products/by-type/microarray-kits/infinium-mouse-methylation.html) and the associated manifest (https://emea.support.illumina.com/downloads/infinium-mouse-methylation-manifest-file-bpm.html).

**Comment by lutsik** [comment]
Hi guys.

I already have a branch where the import of the mouse array is essentially implemented. Maxi (a PhD student over here) has managed to build an annotation package.

Should I first commit the branch so we can look at it together and discuss?

**Comment by lutsik** [comment]
see feature/MouseMethylationBeadChip

**Comment by schmic05** [comment]
Hi Pavlo,

That's great news. Yes, let's have a look at the branch together and maybe discuss it afterwards. Thanks for developing this and greetings to Maxi.

**Comment by lutsik** [comment]
Sure, will do ))

**Comment by lutsik** [comment]
The branch alone will not help, since you also need an updated RnBeads.mm10. The latter is still in the making, hang on a little longer...

**Comment by RinconFer** [comment]
Hi thanks for the fantastic package, 

I am trying to use it to analyze a mouse dataset, however I have been unable to install the development version because it is asking for the R version 4.4 and I can't install that without really breaking all my other pipelines to analyze other type of data. Is there a way to use the package in mouse data without being force to install the development version of R?

**Comment by schmic05** [comment]
Hi @RinconFer 

As far as I know, this will unfortunately not be possible. However, I would suggest that you look into (bio)conda (https://bioconda.github.io/), which makes it easy to have multiple different R installations in parallel. 

Hope that helps,

Michael
